spring:
  profiles:
    active: local
  jackson:
    property-naming-strategy: SNAKE_CASE # 驼峰转为下划线
    default-property-inclusion: non_null
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
  servlet:
    multipart:
      maxFileSize: "200MB"
      location: /data/tmp
  reactor:
    debug-agent:
      enabled: true
  flyway:
    baseline-description: baseline init
    baseline-on-migrate: true
    Schema: public
    locations: classpath:db/migration/
    baseline-version: 1.0.101
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: pylonHikariCP
      max-lifetime: 900000
      connection-timeout: 15000
      connection-test-query: SELECT 1
mybatis:
  # Mapper文件扫描路径
  mapper-locations: classpath:mapper/*.xml
  # 实体类别名扫描
  type-aliases-package: com.github.tkmybatis.dao.entity
  configuration:
    # 开启驼峰命名
    map-underscore-to-camel-case: true
    # 输出运行信息到控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
